package net.condorcraft110.seashell;

public enum EventType
{
	SEASHELL_STARTUP,
	SEASHELL_SHUTDOWN,
	COMMAND_STARTED,
	COMMAND_EXECUTED,
	COMMAND_FAILED,
	ATTEMPT_PLUGIN_LOAD,
	PLUGIN_LOAD_FAILED,
	PLUGIN_LOADED,
	TEXT_LOGGED,
	COMMAND_REGISTERED;
}
